name: Deploy MARFA-webapp Frontend

on:
  workflow_dispatch:

jobs:
  build_and_push:

    name: Push frontend image to Selectel Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3


      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Selectel
        uses: docker/login-action@v3
        with:
          registry: cr.selcloud.ru
          username: token
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Push to container registry
        uses: docker/build-push-action@v4
        with:
          context: ./interface
          push: true
          tags: cr.selcloud.ru/marfa/marfa-frontend:latest
